<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{{ $title }}</title>

    <style>
        @page {
            margin: 24px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9px;
            color: #222;
        }

        h1 {
            margin: 0 0 4px 0;
            font-size: 18px;
        }

        .meta {
            margin-bottom: 18px;
            color: #555;
        }

        .section {
            margin-bottom: 20px;
            page-break-inside: auto;
        }

        .section-title {
            margin: 0 0 6px 0;
            padding-bottom: 4px;
            border-bottom: 1px solid #999;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: auto;
        }

        th,
        td {
            border: 1px solid #ccc;
            padding: 4px;
            vertical-align: top;
            word-wrap: break-word;
        }

        th {
            background: #f2f2f2;
            font-weight: bold;
            text-align: left;
        }

        tr {
            page-break-inside: avoid;
        }

        .empty {
            color: #777;
            font-style: italic;
        }

        .footer {
            margin-top: 20px;
            font-size: 8px;
            color: #666;
        }
    </style>
</head>

<body>
    <h1>{{ $title }}</h1>

    <div class="meta">
        Reporting period:
        {{ $period['from'] }}
        to
        {{ $period['to'] }}
        ({{ $period['days'] }} days)
    </div>

    @foreach ($sections as $section)
        <div class="section">
            <h2 class="section-title">
                {{ $section['title'] }}
            </h2>

            @if (count($section['rows']) === 0)
                <div class="empty">
                    No records for this section.
                </div>
            @else
                <table>
                    <thead>
                        <tr>
                            @foreach ($section['headers'] as $header)
                                <th>
                                    {{ $header }}
                                </th>
                            @endforeach
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($section['rows'] as $row)
                            <tr>
                                @foreach ($row as $value)
                                    <td>
                                        {{ $value }}
                                    </td>
                                @endforeach
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    @endforeach

    <div class="footer">
        Generated by SmartCare-AI on
        {{ $generatedAt->format('Y-m-d H:i:s') }}.
        This report reflects recorded system evidence for the selected reporting period.
    </div>
</body>
</html>